### ISSUE TITLE
Missing code snipets for Delegated Market order

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove-docs#25]
Code snippets (solidity, events, revert strings and ethers.js) examples are missing in the section describing `marketOrderFor` (https://app.gitbook.com/o/-MdT1rJl02j-iWnZq5Wo/s/-MdT1ftsp-ASVL0f7MSf/technical-references/taking-and-making-offers/delegate-takers)

**Comment by dontrolle** [comment]
Seems fixed on the `develop` branch.
