### ISSUE TITLE
Missing js snippet for `newOffer`

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove-docs#26]
Missing the ethers.js code snippet for new offer:
https://app.gitbook.com/o/-MdT1rJl02j-iWnZq5Wo/s/-MdT1ftsp-ASVL0f7MSf/technical-references/taking-and-making-offers/reactive-offer

**Comment by dontrolle** [comment]
(Also - the ethers.js code snippet for newOffer https://docs.mangrove.exchange/contracts/technical-references/taking-and-making-offers/reactive-offer/)
