### ISSUE TITLE
Left-hand menu for glossary should always be ordered by term, not filename

### ISSUE THREAD

**Issue by dontrolle** [mangrovedao/mangrove-docs#55]
The left-hand menu for the glossary at https://docs.mangrove.exchange/glossary is currently ordered by filename (which is equal to the term ids). 

Instead, the left-hand menu should be ordered by the term titles.

**Comment by DavidRod1865** [comment]
Good afternoon! I don't mind helping with this issue!

**Comment by dontrolle** [comment]
> Good afternoon! I don't mind helping with this issue!

HI @DavidRod1865, that sounds cool. PR's are welcome.

I couldn't immediately find any simple of way doing this myself, but I may definitely have overlooked something. 😊
