### ISSUE TITLE
Search engine does not index code snippets

### ISSUE THREAD

**Issue by peterMangrove** [mangrovedao/mangrove-docs#87]
### Example
When searching for the event "OfferSuccess", the search engine does not find the instance where OfferSuccess is in a code snippet, here e.g., https://docs.mangrove.exchange/contracts/technical-references/taking-and-making-offers/taker-order/#market-order, under the events tab, the OfferSuccess is described, but not found when searching.

**Comment by dontrolle** [comment]
This is probably an issue with the Algolia search engine - and may require configuration of that, or - ultimately - switching search engine.

**Comment by dontrolle** [comment]
Given that this is an issue with the search engine, we can hope that this is fixed in Docusaurus v3 (haven't checked), or else, pragmatically we should let this issue rest for now. Since I've reported https://github.com/mangrovedao/mangrove-docs/issues/205, I'll close this issue.
